parameters:
  name: null
  pool: {}
  matrix: {}
  dockerClientOS: null
  buildJobTimeout: 60
  customInitSteps: []
  noCache: false
  internalProjectName: null
  publicProjectName: null
  internalVersionsRepoRef: null
  publicVersionsRepoRef: null

jobs:
- job: ${{ parameters.name }}
  condition: and(${{ parameters.matrix }}, not(canceled()), in(dependencies.PreBuildValidation.result, 'Succeeded', 'SucceededWithIssues', 'Skipped'))
  dependsOn:
  - PreBuildValidation
  - CopyBaseImages
  - GenerateBuildMatrix
  pool: ${{ parameters.pool }}
  strategy:
    matrix: $[ ${{ parameters.matrix }} ]
  timeoutInMinutes: ${{ parameters.buildJobTimeout }}
  variables:
    imageBuilderDockerRunExtraOptions: $(build.imageBuilderDockerRunExtraOptions)
    versionsRepoPath: versions
    sbomDirectory: $(Build.ArtifactStagingDirectory)/sbom
    ${{ if eq(parameters.noCache, false) }}:
      versionsBasePath: $(versionsRepoPath)/
      pipelineDisabledCache: false
    ${{ if eq(parameters.noCache, true) }}:
      versionsBasePath: ""
      pipelineDisabledCache: true
  steps:
  - checkout: none
  - script: ls -R /home/robox/agent/_work
